<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\modules\TicketManagement\NetMetric.CRM.TicketManagement.Application\NetMetric.CRM.TicketManagement.Application.csproj" />
    <ProjectReference Include="..\..\..\src\modules\TicketManagement\NetMetric.CRM.TicketManagement.Infrastructure\NetMetric.CRM.TicketManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\search\src\NetMetric.Search.Contracts\NetMetric.Search.Contracts.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  
</Project>
