<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\NetMetric.Search.API\NetMetric.Search.API.csproj" />
    <ProjectReference Include="..\..\src\NetMetric.Search.Application\NetMetric.Search.Application.csproj" />
    <ProjectReference Include="..\..\src\NetMetric.Search.Infrastructure\NetMetric.Search.Infrastructure.csproj" />
  </ItemGroup>
</Project>
