import type { ToolCatalog } from "./catalog-types";

const MB = 1024 * 1024;

export const fallbackCatalog: ToolCatalog = {
  categories: [
    {
      slug: "image",
      title: "Image Tools",
      description: "Convert and optimize images directly in the browser.",
      sortOrder: 1,
    },
    {
      slug: "developer",
      title: "Developer Tools",
      description: "Utilities for quick formatting and generation workflows.",
      sortOrder: 2,
    },
  ],
  tools: [
    {
      slug: "qr-generator",
      title: "QR Generator",
      description: "Generate downloadable QR images from text or URLs.",
      categorySlug: "image",
      executionMode: "browser",
      availabilityStatus: "enabled",
      isEnabled: true,
      acceptedMimeTypes: [],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "QR Generator - NetMetric Tools",
      seoDescription: "Generate QR images in your browser and download instantly.",
    },
    {
      slug: "png-to-jpg",
      title: "PNG to JPG",
      description: "Convert PNG files to JPG format in the browser.",
      categorySlug: "image",
      executionMode: "browser",
      availabilityStatus: "enabled",
      isEnabled: true,
      acceptedMimeTypes: ["image/png"],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "PNG to JPG Converter - NetMetric Tools",
      seoDescription: "Convert PNG to JPG locally with browser-side processing.",
    },
    {
      slug: "jpg-to-png",
      title: "JPG to PNG",
      description: "Convert JPG files to PNG format in the browser.",
      categorySlug: "image",
      executionMode: "browser",
      availabilityStatus: "enabled",
      isEnabled: true,
      acceptedMimeTypes: ["image/jpeg"],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "JPG to PNG Converter - NetMetric Tools",
      seoDescription: "Convert JPG to PNG locally with browser-side processing.",
    },
    {
      slug: "pdf-compress",
      title: "PDF Compress",
      description: "Reduce PDF file size with quality-aware compression options.",
      categorySlug: "image",
      executionMode: "future",
      availabilityStatus: "coming-soon",
      isEnabled: false,
      acceptedMimeTypes: ["application/pdf"],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "PDF Compress - NetMetric Tools",
      seoDescription: "Compress PDF files with privacy-first workflows.",
    },
    {
      slug: "image-resize",
      title: "Image Resize",
      description: "Resize images to exact dimensions while preserving quality.",
      categorySlug: "image",
      executionMode: "future",
      availabilityStatus: "coming-soon",
      isEnabled: false,
      acceptedMimeTypes: ["image/png", "image/jpeg", "image/webp"],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "Image Resize - NetMetric Tools",
      seoDescription: "Resize image dimensions with pixel-level control.",
    },
    {
      slug: "json-format",
      title: "JSON Formatter",
      description: "Validate and format JSON text for readable output.",
      categorySlug: "developer",
      executionMode: "future",
      availabilityStatus: "coming-soon",
      isEnabled: false,
      acceptedMimeTypes: ["application/json", "text/plain"],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "JSON Formatter - NetMetric Tools",
      seoDescription: "Format and validate JSON in a fast browser tool.",
    },
    {
      slug: "uuid-generator",
      title: "UUID Generator",
      description: "Generate UUIDs for development and integration use cases.",
      categorySlug: "developer",
      executionMode: "future",
      availabilityStatus: "coming-soon",
      isEnabled: false,
      acceptedMimeTypes: [],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "UUID Generator - NetMetric Tools",
      seoDescription: "Generate secure UUID values instantly in the browser.",
    },
    {
      slug: "password-generator",
      title: "Password Generator",
      description: "Generate strong passwords with configurable complexity.",
      categorySlug: "developer",
      executionMode: "future",
      availabilityStatus: "coming-soon",
      isEnabled: false,
      acceptedMimeTypes: [],
      guestMaxFileBytes: 5 * MB,
      authenticatedMaxSaveBytes: 10 * MB,
      seoTitle: "Password Generator - NetMetric Tools",
      seoDescription: "Create strong passwords with privacy-first defaults.",
    },
  ],
};
