apiVersion: v1
kind: Service
metadata:
  name: public-web
  namespace: netmetric
  labels:
    app.kubernetes.io/name: public-web
    app.kubernetes.io/part-of: netmetric
spec:
  selector:
    app.kubernetes.io/name: public-web
  ports:
    - name: http
      port: 80
      targetPort: http
