apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-web
  namespace: netmetric
  labels:
    app.kubernetes.io/name: public-web
    app.kubernetes.io/part-of: netmetric
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - netmetric.net
        - www.netmetric.net
      secretName: public-web-netmetric-tls
  rules:
    - host: netmetric.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-web
                port:
                  number: 80
    - host: www.netmetric.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-web
                port:
                  number: 80
