import type { AppSidebarNavIcon } from "@netmetric/ui/client";
import {
  Activity,
  AlarmClock,
  BarChart3,
  BookOpen,
  Bot,
  Building2,
  Calendar,
  CheckSquare,
  Contact,
  FileSignature,
  FileText,
  FolderOpen,
  GitBranch,
  Handshake,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Megaphone,
  MessagesSquare,
  Package,
  Plug,
  Settings,
  Shield,
  Shuffle,
  Sparkles,
  Tags,
  Target,
  Ticket,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
  Workflow,
} from "lucide-react";

import type { CrmModuleIconKey } from "@/features/modules/module-registry";

export const crmNavIcons: Record<CrmModuleIconKey, AppSidebarNavIcon> = {
  "layout-dashboard": LayoutDashboard,
  users: Users,
  "building-2": Building2,
  contact: Contact,
  sparkles: Sparkles,
  "user-plus": UserPlus,
  handshake: Handshake,
  target: Target,
  "git-branch": GitBranch,
  "file-text": FileText,
  "trending-up": TrendingUp,
  package: Package,
  inbox: Inbox,
  ticket: Ticket,
  "alarm-clock": AlarmClock,
  shuffle: Shuffle,
  megaphone: Megaphone,
  "messages-square": MessagesSquare,
  calendar: Calendar,
  "file-signature": FileSignature,
  "folder-open": FolderOpen,
  wallet: Wallet,
  plug: Plug,
  "book-open": BookOpen,
  "list-checks": ListChecks,
  workflow: Workflow,
  "bar-chart-3": BarChart3,
  bot: Bot,
  tags: Tags,
  shield: Shield,
  "check-square": CheckSquare,
  activity: Activity,
  settings: Settings,
};

export const crmNavIconColors: Record<CrmModuleIconKey, string> = {
  "layout-dashboard": "text-blue-500",
  users: "text-cyan-500",
  "building-2": "text-emerald-500",
  contact: "text-teal-500",
  sparkles: "text-violet-500",
  "user-plus": "text-green-500",
  handshake: "text-lime-500",
  target: "text-rose-500",
  "git-branch": "text-indigo-500",
  "file-text": "text-sky-500",
  "trending-up": "text-yellow-500",
  package: "text-orange-500",
  inbox: "text-fuchsia-500",
  ticket: "text-amber-500",
  "alarm-clock": "text-red-500",
  shuffle: "text-purple-500",
  megaphone: "text-pink-500",
  "messages-square": "text-cyan-500",
  calendar: "text-teal-500",
  "file-signature": "text-blue-500",
  "folder-open": "text-lime-500",
  wallet: "text-emerald-500",
  plug: "text-violet-500",
  "book-open": "text-orange-500",
  "list-checks": "text-green-500",
  workflow: "text-indigo-500",
  "bar-chart-3": "text-yellow-500",
  bot: "text-fuchsia-500",
  tags: "text-pink-500",
  shield: "text-red-500",
  "check-square": "text-sky-500",
  activity: "text-amber-500",
  settings: "text-slate-500",
};
