<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\src\NetMetric.CRM.Core\NetMetric.CRM.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\packages\dotnet\src\NetMetric.CurrentUser\NetMetric.CurrentUser.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\packages\dotnet\src\NetMetric.Exceptions\NetMetric.Exceptions.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\packages\dotnet\src\NetMetric.Media\NetMetric.Media.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\packages\dotnet\src\NetMetric.Pagination\NetMetric.Pagination.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\packages\dotnet\src\NetMetric.Repository\NetMetric.Repository.csproj" />
    <ProjectReference Include="..\NetMetric.CRM.ProductCatalog.Contracts\NetMetric.CRM.ProductCatalog.Contracts.csproj" />
    <ProjectReference Include="..\NetMetric.CRM.ProductCatalog.Domain\NetMetric.CRM.ProductCatalog.Domain.csproj" />
  </ItemGroup>

</Project>
